version: '3'

services:
  sqlite3:
    container_name: sqlite3_container_test
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
   ## volumes:
      #Modify following line
     ## - path-to/your/databases/sqlite3:/root/db/
    ports:
      - '9000:9000' # expose ports - HOST:CONTAINER
    restart: unless-stopped
  frontend:
        
        build: ./login-main
            # context: .
            # dockerfile: Dockerfile.dev
        command: npm run start
        container_name: login-main
        ports:
            - "3000:3000"        
        volumes: 
            - ./:/login-main
            - /login-main/node_modules
  server:
    container_name: backend
    build: ./server
    command: uvicorn sql_app.main:app --port 80 --reload
    ports:
      - "5000:80"
    environment:
      - SQLITE_PATH=/sql_app.db